"""Established one-to-many relationship between movies and reviews

Revision ID: cc0cecb512ca
Revises: 23a6adb4cf40
Create Date: 2022-11-09 14:08:07.905912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0cecb512ca'
down_revision = '23a6adb4cf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'movie_id')
    # ### end Alembic commands ###
